==============================Numeric Parameters==============================
channel 0.2                    Keyword, Ubulk                
0.2 0.2 0.2                    dx,dy,dz                      
1000 1000000 0.72 0.6 0.0034   dens, RE, Pr, turb Schmidt, beta
0.0 0.0 -9.8                   gx,gy,gz                      
3                              convection_scheme(1=Exp.Euler,2=AdamsBashfort,3=RK2,4=RK3)
3                              diffusion_scheme(1=Imp.Euler,2=CrankNicholson,3=ExplicitRungeKuttaDiff)
WENO                           differencing(1=2ndCDS,2=4thCDS,3=WENO)
2                              solver(1=sip,2=mg)            
1 2                            multigrid step (ngrid), multigrid iteration scheme(1=GSS,2=TDMA,3=RBGSS)
30 2 1                         multigrid maximum iteration per time step, restriction iter, prolongation iter
0.2 F 25 0.2                   dt, variable(T)/fixed(F) dt, sweeps, safety_factor
3 yes yes 3                    itime_end, restart, reinitmean, n_out
yes 2                          LTRANSIENT, results output    
20 1e-05 5 5 5 20              niter, eps, nswp(1), nswp(2), nswp(3), nswp(4)
===========================Flow Boundary Conditions==========================
inflow                         West Boundary Condition (1= Inflow; 12=1/7th power law; 7=prescribed inflow; 8=SEM)
outflow                        East Boundary Condition (2= Outflow, 2=NeumannBC(NBC) 21= ConvectiveBC(CBC))
slip                           South Boundary Condition (3= Slip Condition)
slip                           North Boundary Condition (4= No-Slip Condition)
slip                           Bottom Boundary Condition (5= Periodic Condition)
slip                           Top Boundary Condition (61=smooth log law; 62=rough log law; 63=1/6th law; 64=1/7th law; 65=1/8th law)
n 62                           Friction coefficient (n:manning;k:equivalent sand; only if bc=62)
F 5000                         save inflow data (precursor sim.) ; number of inlets
============================Synthetic Eddy Method============================
12                             Velocity profile:1=Uniform; 12=1/7th PL
0.1                            Turbulence intensity          
1000                           Number inlet profiles         
==============================Modelling Options==============================
T 60.0 61.0 0.0                time_averaging, t_start_averaging1, t_start_averaging2, noise
yes WAE                        SGS-model,1=Smagorinsky,2=WALE,3=OneEqnModel,4=k-eps model (RANS)
2 2                            LMR (1=old ghost cell approach, 2=new ghost cell aplsproach),normal ghost velocity interpolation(1=2nd-order,2=4th-order)
off yes F                      LIMB,LENERGY,LROUGH           
yes 1 y n                      LPT, OpenMP threads, LSCALAR, LActiveScalar
2                              pl_ex (# of extra ghost planes. pl_ex=0 -> blocks have only 1 ghost layer)
293 293                        Th, Tc                        
=========================Energy Boundary Conditions==========================
F F 3 0.001 0.02 22 0.65       L_LSM,reinit,ntime_reinit,reldif_LSM,length,accuracy (HJ_ENO=11,HJ_WENO=22)
F                              L_ENDS                        
F F                            L_LSMbase,L_LSMinit           
F F                            L_anim_phi,L_anim_grd         
1000.0 1.205 1e-06 1.5e-05     densl,densg,nul,nug           
0.0 0.0 -9.8                   gx,gy,gz                      
0.0                            slope                         
===========================Free Surface Parameters===========================
1                              num of time series points     
1 10 10 10                     point #1                      
